### ISSUE TITLE
shit bot fix

### ISSUE THREAD

**Issue by dog-song** [xmatmen/DiscordChaos#4]
fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix fix

**Comment by xmatmen** [comment]
no u
